# Name of the bucket in MinIO
bucket: openim
# Access key ID for MinIO authentication
accessKeyID: root
# Secret access key for MinIO authentication
secretAccessKey: openIM123
# Session token for MinIO authentication (optional)
sessionToken: 
# Internal address of the MinIO server
internalAddress: 172.31.29.232:10005
# External address of the MinIO server, accessible from outside. Supports both HTTP and HTTPS using a domain name
externalAddress: http://182.92.236.71:10005
# Flag to enable or disable public read access to the bucket
publicRead: false


